# Generated by Django 3.2.3 on 2021-08-09 01:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(choices=[('CS', '컴퓨터공학과'), ('ME', '기계시스템디자인공학과'), ('NE', '신소재공학과'), ('CHE', '화학공학과'), ('CEE', '건설환경공학과'), ('EE', '전자전기공학부'), ('DE', '산업데이터공학과'), ('Law', '법학부'), ('Mus', '뮤지컬전공'), ('PM', '실용음악전공'), ('Ar', '건축학과'), ('IAr', '실내건축학과'), ('CE', '도시공학과'), ('Kor', '국어국문학과'), ('Eng', '영어영문학과'), ('Fra', '불어불문학과'), ('Ger', '독어독문학과'), ('ArtFm', '미술대학자율전공'), ('Art', '예술학과'), ('Sc', '조소과'), ('Pa', '회화과'), ('OPa', '동양화가'), ('En', '판화과'), ('Ed', '교육학과'), ('KEd', '국어교육과'), ('EEd', '영어교육과'), ('MEd', '수학교육과'), ('HEd', '역사교육과'), ('VD', '시각디자인학과'), ('InD', '산업디자인학과'), ('PG', '도예유리과'), ('WF', '목조형가구학과'), ('MD', '금속조형디자인과'), ('FD', '섬유미술패션디자인과'), ('Man', '경영학과'), ('Ec', '경제학과'), ('SFm', '서울캠퍼스자율전공'), ('DM', '디자인경영융합학부'), ('DC', '디자인컨버전스학부'), ('Ani', '영상애니메이션학부'), ('GS', '게임소프트웨어공학전공'), ('GD', '게임그래픽디자인전공'), ('STFm', '과학기술대학자율전공'), ('ArD', '건축디자인과'), ('ArE', '건축공학과'), ('MIE', '기계정보공학과'), ('ShE', '조선해양공학과'), ('BC', '바이오화학공학과'), ('NN', '나노신소재공학과'), ('ECE', '전자전기융합공학과'), ('SCE', '소프트웨어융합공학과'), ('GM', '글로벌경영학과'), ('FI', '금융보험학과'), ('Ac', '회계학과'), ('Ad', '광고홍보학부'), ('IS', '산업스포츠학과'), ('SjFm', '세종캠퍼스자율전공')], default='CS', max_length=5)),
                ('studentNum', models.CharField(max_length=10)),
                ('campus', models.CharField(choices=[('SC', '서울캠퍼스'), ('SJC', '세종캠퍼스'), ('DHN', '대학로캠퍼스')], default='SC', max_length=50)),
                ('schoolEmail', models.CharField(max_length=50)),
                ('websiteName', models.CharField(blank=True, max_length=150, null=True)),
                ('websiteURL', models.CharField(blank=True, max_length=150, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='_account_customuser_followers_+', to=settings.AUTH_USER_MODEL)),
                ('followings', models.ManyToManyField(blank=True, related_name='_account_customuser_followings_+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Univ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityActivity', models.CharField(blank=True, max_length=50, null=True)),
                ('universityTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('university_YearStart', models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=10, null=True)),
                ('university_MonthStart', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3, null=True)),
                ('university_YearEnd', models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=10, null=True)),
                ('university_MonthEnd', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3, null=True)),
                ('university_RoleAchievement', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('careerYearStart', models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=10, null=True)),
                ('careerMonthStart', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3, null=True)),
                ('careerYearEnd', models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=10, null=True)),
                ('careerMonthEnd', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3, null=True)),
                ('careerRoleAchievement', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
