# Generated by Django 3.2.3 on 2021-08-10 12:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(choices=[('컴퓨터공학과', '컴퓨터공학과'), ('기계시스템디자인공학과', '기계시스템디자인공학과'), ('신소재공학과', '신소재공학과'), ('화학공학과', '화학공학과'), ('건설환경공학과', '건설환경공학과'), ('전자전기공학부', '전자전기공학부'), ('산업데이터공학과', '산업데이터공학과'), ('법학부', '법학부'), ('뮤지컬전공', '뮤지컬전공'), ('실용음악전공', '실용음악전공'), ('건축학과', '건축학과'), ('실내건축학과', '실내건축학과'), ('도시공학과', '도시공학과'), ('국어국문학과', '국어국문학과'), ('영어영문학과', '영어영문학과'), ('불어불문학과', '불어불문학과'), ('독어독문학과', '독어독문학과'), ('미술대학자율전공', '미술대학자율전공'), ('예술학과', '예술학과'), ('조소과', '조소과'), ('회화과', '회화과'), ('동양화가', '동양화가'), ('판화과', '판화과'), ('교육학과', '교육학과'), ('국어교육과', '국어교육과'), ('영어교육과', '영어교육과'), ('수학교육과', '수학교육과'), ('역사교육과', '역사교육과'), ('시각디자인학과', '시각디자인학과'), ('산업디자인학과', '산업디자인학과'), ('도예유리과', '도예유리과'), ('목조형가구학과', '목조형가구학과'), ('금속조형디자인과', '금속조형디자인과'), ('섬유미술패션디자인과', '섬유미술패션디자인과'), ('경영학과', '경영학과'), ('경제학과', '경제학과'), ('서울캠퍼스자율전공', '서울캠퍼스자율전공'), ('디자인경영융합학부', '디자인경영융합학부'), ('디자인컨버전스학부', '디자인컨버전스학부'), ('영상애니메이션학부', '영상애니메이션학부'), ('게임소프트웨어공학전공', '게임소프트웨어공학전공'), ('게임그래픽디자인전공', '게임그래픽디자인전공'), ('과학기술대학자율전공', '과학기술대학자율전공'), ('건축디자인과', '건축디자인과'), ('건축공학과', '건축공학과'), ('기계정보공학과', '기계정보공학과'), ('조선해양공학과', '조선해양공학과'), ('바이오화학공학과', '바이오화학공학과'), ('나노신소재공학과', '나노신소재공학과'), ('전자전기융합공학과', '전자전기융합공학과'), ('소프트웨어융합공학과', '소프트웨어융합공학과'), ('글로벌경영학과', '글로벌경영학과'), ('금융보험학과', '금융보험학과'), ('회계학과', '회계학과'), ('광고홍보학부', '광고홍보학부'), ('산업스포츠학과', '산업스포츠학과'), ('세종캠퍼스자율전공', '세종캠퍼스자율전공')], default='CS', max_length=30)),
                ('studentNum', models.CharField(choices=[('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21')], default=21, max_length=10)),
                ('campus', models.CharField(choices=[('SC', '서울캠퍼스'), ('SJC', '세종캠퍼스'), ('DHN', '대학로캠퍼스')], default='SC', max_length=50)),
                ('schoolEmail', models.CharField(max_length=50)),
                ('websiteName', models.CharField(blank=True, max_length=150, null=True)),
                ('websiteURL', models.CharField(blank=True, max_length=150, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='_account_customuser_followers_+', to=settings.AUTH_USER_MODEL)),
                ('followings', models.ManyToManyField(blank=True, related_name='_account_customuser_followings_+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Univ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityActivity', models.CharField(blank=True, max_length=50, null=True)),
                ('universityTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('university_YearStart', models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=10, null=True)),
                ('university_MonthStart', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3, null=True)),
                ('university_YearEnd', models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=10, null=True)),
                ('university_MonthEnd', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3, null=True)),
                ('university_RoleAchievement', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('careerYearStart', models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=10, null=True)),
                ('careerMonthStart', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3, null=True)),
                ('careerYearEnd', models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=10, null=True)),
                ('careerMonthEnd', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3, null=True)),
                ('careerRoleAchievement', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
