# Generated by Django 3.2.6 on 2021-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('management', '총무 및 사무'), ('business', '영업'), ('PerDepart', '인사'), ('customerC', '고객상담'), ('marketing', '마케팅'), ('trade', '유통 및 무역'), ('design', '디자인'), ('develop', '개발'), ('judicial', '법무 및 특허'), ('strategy', '전략 및 기획'), ('financial', '재무 및 회계'), ('sales', '구매 및 조달'), ('service', '서비스'), ('profession', '전문직'), ('medical', '의료 및 제약'), ('educ', '교육직'), ('construct', '건설 및 인테리어'), ('research', '연구 및 생산, 제조'), ('media', '미디어'), ('etc', '특수')], default='develop', max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('hashtag', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=30)),
                ('career1Title', models.CharField(max_length=50)),
            ],
        ),
    ]
